export SCUTTLESPACE_TESTDB_NAME="scuttlespacetestdb"
export SCUTTLESPACE_TESTDB_HOST="127.0.0.1"
export SCUTTLESPACE_TESTDB_PASSWORD="secret"
export SCUTTLESPACE_TESTDB_PORT=5432
export SCUTTLESPACE_TESTDB_USER="postgres"