export SCUTTLESPACE_DB_NAME="scuttlespacetestdb"
export SCUTTLESPACE_DB_HOST="127.0.0.1"
export SCUTTLESPACE_DB_PASSWORD="secret"
export SCUTTLESPACE_DB_PORT=5432
export SCUTTLESPACE_DB_USER="postgres"